apiVersion: apps/v1
kind: Deployment
metadata:
  name: articles-deployment
  labels:
    app: articles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: articles
  template:
    metadata:
      labels:
        app: articles
    spec:
      containers:
      - name: articles
        image: streamio.azurecr.io/streamio-backend_articles:v1
        env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: articles-secrets
                key: mongo_uri
          - name: PORT
            value: "3000"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: articles-service
spec:
  selector:
    app: articles
  ports:
    - port: 3000
      targetPort: 3000